BEGIN TRANSACTION;

PRAGMA application_id = 215794801;
PRAGMA user_version = 1;

CREATE TABLE `User` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `UserName` TEXT NOT NULL,
    `Name` TEXT NOT NULL,
    `PasswordHash` TEXT NOT NULL
);

CREATE TABLE `Audit` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `UserID` INTEGER NOT NULL,
    `Action` TEXT NOT NULL,
    `Time` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ExtraData` TEXT,
    FOREIGN KEY (`UserID`) REFERENCES `User`(`ID`)
);

COMMIT;
